# Social Network AD 

We are using the Social network ad dataset. The dataset contains the details of users in a social networking site to find whether a user buys a product by clicking the ad on the site based on their salary, age, and gender.

In [3]:
#importing libraries
import pandas as pd
import numpy as mp
import matplotlib.pyplot as plt


In [4]:
#importing data
data= pd.read_csv('NBDATA.csv')

In [5]:
data

INDEX   USER ID  GENDER  AGE  ESTIMATEDSALARY  PURCHASED
0       0  15624510    MALE   19            19000          0
1       1  15810944    MALE   35            20000          0
2       2  15668575  FEMALE   26            43000          0
3       3  15603246  FEMALE   27            57000          0
4       4  15804002    MALE   19            76000          0
5       5  15728773    MALE   27            58000          0
6       6  15598044  FEMALE   27            84000          0
7       7  15694829  FEMALE   32           150000          1
8       8  15600575    MALE   25            33000          0
9       9  15787311  FEMALE   35            65000          0
10     10  15570769  FEMALE   26            80000          0

In [6]:
data.describe()

INDEX       USER ID        AGE  ESTIMATEDSALARY  PURCHASED
count  11.000000  1.100000e+01  11.000000        11.000000  11.000000
mean    5.000000  1.568105e+07  27.090909     62272.727273   0.090909
std     3.316625  8.982337e+04   5.356390     36894.690429   0.301511
min     0.000000  1.557077e+07  19.000000     19000.000000   0.000000
25%     2.500000  1.560191e+07  25.500000     38000.000000   0.000000
50%     5.000000  1.566858e+07  27.000000     58000.000000   0.000000
75%     7.500000  1.575804e+07  29.500000     78000.000000   0.000000
max    10.000000  1.581094e+07  35.000000    150000.000000   1.000000

In [7]:
data.corr()

INDEX   USER ID       AGE  ESTIMATEDSALARY  PURCHASED
INDEX            1.000000 -0.198056  0.281450         0.530377   0.200000
USER ID         -0.198056  1.000000  0.355527        -0.024560   0.050868
AGE              0.281450  0.355527  1.000000         0.211883   0.303966
ESTIMATEDSALARY  0.530377 -0.024560  0.211883         1.000000   0.788619
PURCHASED        0.200000  0.050868  0.303966         0.788619   1.000000

In [8]:
X = data.iloc[:, [2, 3]].values #2,3 column of data
y = data.iloc[:, -1].values #last column of data


In [9]:
X

array([['MALE', 19],
       ['MALE', 35],
       ['FEMALE', 26],
       ['FEMALE', 27],
       ['MALE', 19],
       ['MALE', 27],
       ['FEMALE', 27],
       ['FEMALE', 32],
       ['MALE', 25],
       ['FEMALE', 35],
       ['FEMALE', 26]], dtype=object)

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [11]:
#Since our dataset containing character variables we have to encode it using LabelEncoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

In [12]:
#splitting the dataset into training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state= 0)

In [13]:
#feature scaling- 
#It is a step of data Pre-Processing which is applied to independent variables to normalize the data within a particular range.

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
 

In [14]:
#training the naive model on the training set
from sklearn.naive_bayes import GaussianNB
classifier= GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [15]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [16]:
y_pred

array([0, 0, 0], dtype=int64)

In [17]:
y_test

array([0, 0, 0], dtype=int64)

In [18]:
#We can evaluate our matrix using the confusion matrix and accuracy score by comparing the predicted and actual test values
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred, y_test)
ac = accuracy_score(y_pred, y_test)

In [19]:
cm

array([[3]], dtype=int64)

In [20]:
ac

1.0