In [1]:
import numpy as np

In [2]:
a= np.array([12, 58, 69, 10])
a

array([12, 58, 69, 10])

In [7]:
b= np.array([(12, 58, 69, 10),(15, 25, 64, 14)])
b

array([[12, 58, 69, 10],
       [15, 25, 64, 14]])

In [9]:
b.reshape(4, 2)
b

array([[12, 58, 69, 10],
       [15, 25, 64, 14]])

In [10]:
a= np.array([12, 58, 69, 10])
b= ([15, 25, 64, 14])
print(a + b)
print(a-b)
print(a*b)
print(a/b)

[ 27  83 133  24]
[-3 33  5 -4]
[ 180 1450 4416  140]
[0.8        2.32       1.078125   0.71428571]
